import { NodeType } from '../types/nodeType';

export const nodes: NodeType[] = [
  {
    id: 'a',
    data: {
      label: 'Dataset A',
      sourceHandles: [
        { id: 'a-s-a' },
        { id: 'a-s-b' },
        { id: 'a-s-c' },
        { id: 'a-s-d' },
        { id: 'a-s-e' },
        { id: 'a-s-f' },
        { id: 'a-s-g' },
        { id: 'a-s-7' },
        { id: 'a-s-8' },
        { id: 'a-s-9' },
        { id: 'a-s-10' },
        { id: 'a-s-11' },
        { id: 'a-s-12' },
        { id: 'a-s-13' },
        { id: 'a-s-14' },
        { id: 'a-s-15' },
        { id: 'a-s-16' },
        { id: 'a-s-17' },
        { id: 'a-s-18' },
        { id: 'a-s-19' },
        { id: 'a-s-20' },
        { id: 'a-s-21' },
        { id: 'a-s-22' },
        { id: 'a-s-23' },
        { id: 'a-s-24' },
        { id: 'a-s-25' },
        { id: 'a-s-26' },
        { id: 'a-s-27' },
        { id: 'a-s-28' },
        { id: 'a-s-29' },
        { id: 'a-s-30' },
        { id: 'a-s-31' },
      ],
      targetHandles: [],
      hasInput: false,
      hasOutput: true,
    },
    position: { x: -37.668799145926016, y: -290.9591039812415 },
    type: 'textUpdater',
    measured: { width: 172, height: 517 },
    selected: false,
    dragging: false,
  },
  {
    id: 'b',
    data: {
      label: 'Dataset B',
      sourceHandles: [],
      targetHandles: [
        { id: 'b-t-a' },
        { id: 'b-t-b' },
        { id: 'b-t-c' },
        { id: 'b-t-3' },
        { id: 'b-t-4' },
        { id: 'b-t-5' },
        { id: 'b-t-6' },
        { id: 'b-t-7' },
        { id: 'b-t-8' },
        { id: 'b-t-9' },
        { id: 'b-t-10' },
        { id: 'b-t-11' },
        { id: 'b-t-12' },
        { id: 'b-t-13' },
        { id: 'b-t-14' },
        { id: 'b-t-15' },
        { id: 'b-t-16' },
        { id: 'b-t-17' },
        { id: 'b-t-18' },
        { id: 'b-t-19' },
        { id: 'b-t-20' },
        { id: 'b-t-21' },
        { id: 'b-t-22' },
      ],
      hasInput: true,
      hasOutput: false,
    },
    position: { x: 397.4548727750696, y: -254.4270064131424 },
    type: 'textUpdater',
    measured: { width: 172, height: 382 },
    selected: false,
    dragging: false,
  },
];
